USE OCTOBER_CLASS_2024

SELECT * FROM 
CUSTOMER_TABLE,ORDER_TABLE,PURCHASE_TABLE;



SELECT DISTINCT REGION, SUM(TOTAL_PROFIT) AS TOTAL_PROFIT
FROM CUSTOMER_TABLE
JOIN
PURCHASE_TABLE
ON
CUSTOMER_TABLE.Order_ID = PURCHASE_TABLE.Order_ID
GROUP BY REGION;


-- KPI 2 - CALCULATE THE TOTAL REVENUE MADE ANNUALLY #

SELECT DISTINCT YEAR(ORDER_DATE) AS YEAR, SUM(TOTAL_REVENUE) AS TOTAL_REVENUE
FROM ORDER_TABLE
JOIN
PURCHASE_TABLE
ON
ORDER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID
GROUP BY YEAR(ORDER_DATE);



-- KPI 3 - COMPARE TOTAL QUANTITY SOLD YEAR BY YEAR FOR EACH ITEM TYPE#

SELECT DISTINCT YEAR(ORDER_DATE), ITEM_TYPE, SUM(UNITS_SOLD) AS UNITS_SOLD
FROM
CUSTOMER_TABLE
LEFT JOIN
ORDER_TABLE

ON
CUSTOMER_TABLE.ORDER_ID = ORDER_TABLE.ORDER_ID

RIGHT JOIN
PURCHASE_TABLE
ON
CUSTOMER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID

GROUP BY YEAR(ORDER_DATE), ITEM_TYPE;



-- KPI 4 - RATE OF REVENUE ACHIEVED IN ALL REGIONS

SELECT DISTINCT REGION,

SUM(TOTAL_REVENUE)*100/(SELECT SUM(TOTAL_REVENUE) AS 'TOTAL REVENUE'
FROM PURCHASE_TABLE) AS '% RATE OF REVENUE'

FROM PURCHASE_TABLE

JOIN
CUSTOMER_TABLE
ON
PURCHASE_TABLE.Order_ID = CUSTOMER_TABLE.Order_ID
GROUP BY REGION;




-- KPI 5 - DETERMINE THE GROSS PROFIT MARGIN FOR EACH ITEM SOLD

SELECT DISTINCT ITEM_TYPE, SUM(TOTAL_REVENUE) AS 'TOTAL REVENUE',
SUM(TOTAL_COST) AS 'TOTAL COST', SUM(TOTAL_REVENUE-TOTAL_COST) AS 'TOTAL PROFIT',
ROUND (SUM(TOTAL_PROFIT*100)/SUM(TOTAL_REVENUE), 2) AS 'GROSS PROFIT MARGIN'
FROM
ORDER_TABLE
JOIN
PURCHASE_TABLE
ON
ORDER_TABLE.Order_ID = PURCHASE_TABLE.ORDER_ID
GROUP BY ITEM_TYPE;




-- KPI 6 - DETERMINE THE AVERAGE AMOUNT OF PROFIT ACHIEVED ANNUALLY

SELECT DISTINCT YEAR(ORDER_DATE) AS 'YEAR', AVG(TOTAL_PROFIT) AS 'AVERAGE ANNUAL PROFIT'
FROM
ORDER_TABLE
JOIN
PURCHASE_TABLE
ON
ORDER_TABLE.Order_ID = PURCHASE_TABLE.ORDER_ID
GROUP BY YEAR(ORDER_DATE);



-- KPI 7 - TOP 4 COUNTRIES WITH THE HIGHEST REVENUE
SELECT DISTINCT COUNTRY, SUM(TOTAL_REVENUE)
FROM
CUSTOMER_TABLE
JOIN
PURCHASE_TABLE
ON
CUSTOMER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID
GROUP BY COUNTRY
ORDER BY SUM(TOTAL_REVENUE) DESC;


-- KPI 7 - TOP 4 COUNTRIES WITH THE LOWEST REVENUE
SELECT DISTINCT COUNTRY, SUM(TOTAL_REVENUE)
FROM
CUSTOMER_TABLE
JOIN
PURCHASE_TABLE
ON
CUSTOMER_TABLE.ORDER_ID = PURCHASE_TABLE.ORDER_ID
GROUP BY COUNTRY
ORDER BY SUM(TOTAL_REVENUE) ASC;



-- KPI 8 - DETERMINE THE REVENUE GROWTH RATE YEAR ON YEAR (YOY)
SELECT 
    YEAR(ORDER_DATE),
    TOTAL_REVENUE,
    LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR(ORDER_DATE)) AS 'PREVIOUS YEAR REVENUE',

    CASE 

        WHEN LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR(ORDER_DATE) IS-NULL THEN NULL
        ELSE ROUND(((TOTAL_REVENUE - LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR(ORDER_DATE))) / LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR(ORDER_DATE)) * 100, 2)
    END AS 'REVENUE GROWTH RATE'

FROM 
    ORDER_TABLE
JOIN
PURCHASE_TABLE
ON
ORDER_TABLE.Order_ID = PURCHASE_TABLE.ORDER_ID

WHERE 
    YEAR(ORDER_DATE) BETWEEN YEAR(2010) - 8 AND YEAR(2017)
ORDER BY 
    YEAR(ORDER_DATE);












